/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ais.parser;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ais.parser.JDBC.ConnectionTest;

public class App {
  private static Logger logger = LoggerFactory.getLogger(App.class);
  
  public String getGreeting() {
    return "APP ON START";
  }

  public static void main(String[] args) {
    logger.info(new App().getGreeting());
    logger.info(ConnectionTest.getConnectionTest());
  } 
}
